Add GUI prompts for GitLab authentication
GitCredentialManager/git-credential-manager pull request #621
Opened 2022-02-09 11:18 UTC by mjcheetham

Add GUI prompts on all platforms for GitLab authentication. GUI prompts are required because if GCM/Git is invoked from an IDE without a terminal, there is no way for the user to authenticate for GitLab.

2022-02-09 17:44 UTC, hickford requested changes

2022-02-09 17:44 UTC, hickford commented on src/shared/GitLab.UI/ViewModels/CredentialsViewModel.cs
> +            BrowserUtils.OpenDefaultBrowser(_environment, "https://about.gitlab.com/");
URL should depend on host, eg. https://gitlab.example.com/users/sign_up or simply https://gitlab.example.com/

2022-02-09 17:45 UTC, hickford commented
> Looks good. Do we want @hickford to give this a quick test?

Works for me.

2022-02-09 17:45 UTC, ldennington approved these changes
B-e-a-utiful!

2022-02-09 17:45 UTC, ldennington commented on src/shared/GitLab.UI.Avalonia/Program.cs
> +            // Dispatcher.Create and Run.
Nit: should this be `Dispatcher.Initialize`?

2022-02-09 17:53 UTC, hickford requested changes

2022-03-02 15:37 UTC, mjcheetham commented on src/shared/GitLab.UI.Avalonia/Views/CredentialsView.axaml
> +            <Image Source="../Assets/gitlab-logo-gray-rgb.png"
I've updated the PR to now use a SVG-based rendering of the "fox" logo, and the logotype "GitLab", separately.

We now hide the logo when it's not gitlab.com.

2022-03-02 15:39 UTC, mjcheetham commented
New screenshots with SVG-based logo and logotype, as well as for gitlab.com and custom instances (for both Avalonia and WPF implementations).

gitlab.com|Other Instances
-|-
![image](https://user-images.githubusercontent.com/5658207/156394920-cdeb7106-6c62-4ebd-9429-592e7bd60063.png)<br/>![image](https://user-images.githubusercontent.com/5658207/156394932-8f40f33e-f4e4-4460-9380-54f46b82168a.png)|![image](https://user-images.githubusercontent.com/5658207/156395052-7cabd7ad-10e0-4512-8639-33029d99ade1.png)<br/>![image](https://user-images.githubusercontent.com/5658207/156395034-dbb49d36-7b73-4647-9f1b-6f3fdc1ffdad.png)

2022-03-02 15:59 UTC, merged