Pass through DOTNET_ROOT and use it as prefix to find dotnet
GitCredentialManager/git-credential-manager pull request #685
Opened 2022-05-03 17:20 UTC by easwarh

This commit makes it easier to build on Linux from source. Related to #606, but
applies to x64 builds as well.

Signed-off-by: Easwar Hariharan <easwar.hariharan@microsoft.com>

2022-05-04 12:25 UTC, mjcheetham requested changes
Hello 👋!

Thanks for the contribution. I'm in favour of making it easier to build GCM on more platforms, but I have one concern about this change as it stands.

The `$DOTNET_ROOT` variable is set by the `dotnet` app host executable, which is typically the caller of these scripts (via MSBuild). However in the cases that this script is called directly (not via `dotnet`) then the variable is not set, and the commands being run in this script will be `/dotnet publish ...` which will not resolve correctly.

If we are to accept this then there should be a check that if the `$DOTNET_ROOT` variable is not set, then the script should fall back to invoking `dotnet` and let the shell resolve the executable location.. 
..OR add something like this to explicitly resolve:

```shell
if [ -z "$DOTNET_ROOT" ]; then
    DOTNET_ROOT="$(dirname $(which dotnet))"
fi
```

2022-05-04 16:49 UTC, easwarh commented
Hi @mjcheetham, that's a great call out, thanks for the feedback! I'll fix this up, would you rather have a fixup commit (commit --fixup), a new commit, or an amendment to the existing commit (commit --amend)?

2022-05-10 05:24 UTC, ldennington commented
@easwarh - I know you directed your question at Matthew, but FWIW my usual workflow in GCM is to amend my existing commits.

2022-05-11 02:49 UTC, easwarh commented
> @easwarh - I know you directed your question at Matthew, but FWIW my usual workflow in GCM is to amend my existing commits.

Thanks for the headsup. I'll push a merged commit.

2022-05-11 15:07 UTC, mjcheetham approved these changes
Looks good to me!

2022-05-11 15:08 UTC, merged

2024-12-06 00:23 UTC, Osama2535 commented on src/linux/Packaging.Linux/build.sh
> +$DOTNET_ROOT/dotnet publish "$GCM_SRC" \
Oatef4313@gmail.com