Convenience config for several popular GitLab instances
GitCredentialManager/git-credential-manager pull request #867
Opened 2022-09-17 22:46 UTC by hickford

Workaround for #677

2022-09-19 06:47 UTC, dscho approved these changes
That looks great!

2022-09-19 17:23 UTC, ldennington approved these changes
Thanks for elevating this for users! ⭐

2022-09-19 17:23 UTC, ldennington commented on docs/gitlab.md
> +For convenience, here is config for several popular GitLab instances:
```suggestion
For convenience, here are the config commands for several popular GitLab instances:
```

2022-09-19 18:56 UTC, ldennington requested changes
Just came up with one more comment, thank you for bearing with me!

2022-09-19 18:56 UTC, ldennington commented on docs/gitlab.md
> +For convenience, here are the config commands for several popular GitLab instances:
It could also be a good idea to clarify that these instances are community-maintained and are not managed by the GCM project.

2022-09-23 20:36 UTC, ldennington approved these changes
Looks good, thanks @hickford!

2022-09-23 21:06 UTC, merged

2022-09-26 21:04 UTC, hickford commented
Brilliant, thanks for merging.