Fix docs/x.md relative links
GitCredentialManager/git-credential-manager pull request #938
Opened 2022-11-03 09:37 UTC by rendall

Some link references were broken, e.g. `[gcm-wsl]: docs/wsl.md` led to `.../docs/docs/wsl.md` (note 2 `docs` in path) This PR fixes those links to properly point to `.../docs/x.md` (1 `docs` in path)

2022-11-03 13:02 UTC, derrickstolee approved these changes
Clicking the links in the preview didn't work, because it didn't take me to your fork. When I viewed these links from your branch in your fork, they did work. Thanks for these fixes.

2022-11-03 18:13 UTC, ldennington requested changes
Thanks for catching these! I added some suggestions to align with how we format these links in other docs. It's worth considering on our end using absolute paths to avoid these situations in the future, but until then let's stay consistent with the relative paths.

2022-11-03 18:13 UTC, ldennington commented on docs/install.md
> +[gcm-wsl]: /docs/wsl.md
```suggestion
[gcm-credstores]: credstores.md
[gcm-wsl]: wsl.md
```

2022-11-03 18:13 UTC, ldennington commented on docs/install.md
> +[linux-uninstall]: /docs/linux-fromsrc-uninstall.md
```suggestion
[linux-uninstall]: linux-fromsrc-uninstall.md
```

2022-11-03 18:20 UTC, ldennington commented
We have decided to do a pre-release today, so going to take this as-is and address my feedback separately.

2022-11-03 18:20 UTC, merged

2022-12-19 07:12 UTC, rendall commented
Ok. This happened so fast I only noticed there were requested changes now! I'm glad it was resolved.